services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5173:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro